version: "3"
services:
  ixctl_postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: ixctl
      POSTGRES_USER: ixctl
      POSTGRES_PASSWORD: devPASSWORD
    logging:
      options:
        max-size: 100m
        max-file: "3"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433

  ixctl_django:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: "runserver 0.0.0.0:${DJANGO_PORT:-8080}"
    env_file: .env
    ports:
      - "${DJANGO_PORT:-8080}:8080"
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - ../../src:/srv/ixctl/main
    depends_on: 
      - ixctl_postgres

volumes:
  postgres_data:
