version: "3"
services:
  postgres:
    image: "postgres:12"
    env_file: .env
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: "runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    logging:
      options:
        max-size: 100m
        max-file: "3"
    volumes:
      - ../../src:/srv/service/main:Z
      - ../../ars_config:/root/arouteserver
    depends_on:
      - postgres

volumes:
  postgres_data:
