# Generated by Django 3.0.8 on 2020-07-28 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import django_ixctl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', django_handleref.models.CreatedDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_handleref.models.UpdatedDateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('deactivated', 'Deactivated'), ('failed', 'Failed'), ('expired', 'Expired')], default='ok', max_length=12)),
                ('pdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pdb_version', models.PositiveIntegerField(blank=True, null=True)),
                ('ipaddr4', models.CharField(blank=True, max_length=255, null=True, validators=[django_ixctl.validators.validate_ip_v4])),
                ('ipaddr6', models.CharField(blank=True, max_length=255, null=True, validators=[django_ixctl.validators.validate_ip_v6])),
                ('is_rs_peer', models.BooleanField(default=False)),
                ('speed', models.PositiveIntegerField()),
                ('asn', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(default='active', max_length=255)),
                ('type', models.CharField(choices=[('peering', 'peering'), ('ixp', 'ixp'), ('routeserver', 'routeserver'), ('probono', 'probono')], default='peering', max_length=255)),
                ('ix_id', models.ForeignKey(help_text='Internet exchange', on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='django_ixctl.Exchange')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('handleref', django.db.models.manager.Manager()),
            ],
        ),
    ]
