# Generated by Django 2.2.14 on 2020-07-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name': 'Exchange', 'verbose_name_plural': 'Exchanges'},
        ),
        migrations.AlterModelOptions(
            name='exchangemember',
            options={'verbose_name': 'Exchange Member', 'verbose_name_plural': 'Exchange Members'},
        ),
        migrations.AlterField(
            model_name='exchangemember',
            name='ix_id',
            field=models.ForeignKey(help_text='Exchanges', on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='django_ixctl.Exchange'),
        ),
        migrations.AlterModelTable(
            name='exchange',
            table='django_ixctl_ix',
        ),
        migrations.AlterModelTable(
            name='exchangemember',
            table='django_ixctl_ixmember',
        ),
    ]
