# Generated by Django 2.2.17 on 2021-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchange',
            name='slug',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
