# Generated by Django 2.2.17 on 2021-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0002_internetexchange_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='internetexchange',
            constraint=models.UniqueConstraint(fields=('instance', 'slug'), name='unique_slug_instance_pair'),
        ),
    ]
