# Generated by Django 3.2.3 on 2021-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ixctl", "0003_internetexchange_ixf_export_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetexchange",
            name="slug",
            field=models.SlugField(max_length=64),
        ),
    ]
