# Generated by Django 3.2.4 on 2021-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ixctl", "0005_postgres_inet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetexchangemember",
            name="ixf_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("awaiting-cross-connect", "Awaiting cross connect"),
                    ("provisioning", "Provisioning"),
                    ("suspended", "Suspended"),
                    ("pending-deletion", "Pending deletion"),
                ],
                default="active",
                max_length=255,
            ),
        ),
    ]
