# Generated by Django 3.2.4 on 2021-10-06 13:11

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0017_alter_organizationuser_options"),
        ("django_ixctl", "0006_member_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="RsConfGenerate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="source_of_truth",
            field=models.BooleanField(
                default=False,
                help_text="Allows other fullctl services to see ixctl as the source of truth for this exchange",
            ),
        ),
    ]
