# Generated by Django 2.2.14 on 2020-08-01 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import django_inet.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ixctl", "0007_organization_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routeserver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Routeserver name", max_length=255),
                ),
                ("asn", django_inet.models.ASNField(help_text="ASN")),
                (
                    "router_id",
                    django_inet.models.IPAddressField(
                        help_text="Router Id", max_length=39
                    ),
                ),
                (
                    "ars_type",
                    models.CharField(
                        choices=[
                            ("bird", "Bird"),
                            ("bird2", "Bird 2"),
                            ("openbgpd", "OpenBGPD"),
                        ],
                        default="bird",
                        max_length=32,
                    ),
                ),
                (
                    "max_as_path_length",
                    models.IntegerField(
                        default=32, help_text="Max length of AS_PATH attribute."
                    ),
                ),
                (
                    "no_export_action",
                    models.CharField(
                        choices=[
                            ("pass", "Pass (Treat as transitive)"),
                            ("strip", "Strip (Treat as non-transitive)"),
                        ],
                        default="pass",
                        help_text="RFC1997 well-known communities (NO_EXPORT and NO_ADVERTISE)",
                        max_length=8,
                    ),
                ),
                (
                    "graceful_shutdown",
                    models.BooleanField(
                        default=False, help_text="Graceful BGP session shutdown"
                    ),
                ),
            ],
            options={"db_table": "ixctl_rs",},
            managers=[("handleref", django.db.models.manager.Manager()),],
        ),
        migrations.AlterModelTable(name="apikey", table="ixctl_api_key",),
        migrations.AlterModelTable(name="internetexchange", table="ixctl_ix",),
        migrations.AlterModelTable(
            name="internetexchangemember", table="ixctl_member",
        ),
        migrations.AlterModelTable(name="organizationuser", table="ixctl_org_user",),
        migrations.CreateModel(
            name="RouteserverConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "generated",
                    models.DateTimeField(auto_now=True, help_text="Time of generation"),
                ),
                ("body", models.TextField(help_text="Config content")),
                (
                    "routeserver",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routeserver",
                        to="django_ixctl.Routeserver",
                    ),
                ),
            ],
            options={"db_table": "ixctl_rsconf",},
            managers=[("handleref", django.db.models.manager.Manager()),],
        ),
        migrations.AddField(
            model_name="routeserver",
            name="ix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rs_set",
                to="django_ixctl.InternetExchange",
            ),
        ),
    ]
