# Generated by Django 3.2.8 on 2021-10-21 12:25

import django.core.validators
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ixctl", "0008_auto_20211020_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeserverconfig",
            name="rs_response",
            field=models.JSONField(
                blank=True, help_text="Routeserver response", null=True
            ),
        ),
        migrations.AlterField(
            model_name="routeserver",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="ASN",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
