# Generated by Django 3.2.8 on 2021-10-21 12:56

import django.core.validators
import django.db.models.deletion
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ixctl", "0009_auto_20211021_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeserverconfig",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to most recent generate task for this rsconfig object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_routeserver_set",
                to="django_ixctl.rsconfgenerate",
            ),
        ),
        migrations.AlterField(
            model_name="routeserver",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="ASN",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
