# Generated by Django 2.2.14 on 2020-08-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0009_routeserver_extra_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeserverconfig',
            name='routeserver',
        ),
        migrations.AddField(
            model_name='routeserverconfig',
            name='ars_clients',
            field=models.TextField(blank=True, help_text='ARouteserver clients config', null=True),
        ),
        migrations.AddField(
            model_name='routeserverconfig',
            name='ars_general',
            field=models.TextField(blank=True, help_text='ARouteserver general config', null=True),
        ),
        migrations.AddField(
            model_name='routeserverconfig',
            name='rs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsconf', to='django_ixctl.Routeserver'),
        ),
    ]
