# Generated by Django 3.2.12 on 2022-07-20 10:23

import django.core.validators
import django_inet.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_ixctl", "0011_auto_20220711_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routeserver",
            name="asn",
            field=django_inet.models.ASNField(
                help_text="ASN",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routeserver",
            unique_together={("ix", "router_id"), ("ix", "name")},
        ),
    ]
