# Generated by Django 2.2.14 on 2020-08-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0011_auto_20200801_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeserver',
            unique_together={('ix', 'router_id')},
        ),
    ]
