# Generated by Django 3.2.15 on 2023-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0013_auto_20221129_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchange',
            name='verified',
            field=models.BooleanField(default=False, help_text='Exchange ownership has been verified'),
        ),
    ]
