# Generated by Django 2.2.15 on 2020-08-06 16:43

from django.db import migrations
import django_inet.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0013_routeserver_rpki_bgp_origin_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchangemember',
            name='macaddr',
            field=django_inet.models.MacAddressField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='internetexchangemember',
            unique_together={('ipaddr6', 'ix'), ('macaddr', 'ix'), ('ipaddr4', 'ix')},
        ),
    ]
