# Generated by Django 3.2.18 on 2023-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0014_internetexchange_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetexchange',
            name='pdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='PeeringDB id of the equivalent exchange (`ix`) object on their end. Its important to set this when the exchange has the source of truth in fullctl so we know which peeringdb object to override. This is set automatically if the ix was imported from peeringdb.', null=True),
        ),
    ]
