# Generated by Django 2.2.16 on 2020-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0015_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manages_ix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='manages_net',
            field=models.BooleanField(default=True),
        ),
    ]
