# Generated by Django 3.2.18 on 2023-03-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_fullctl', '0031_auto_20230310_2152'),
        ('django_ixctl', '0015_alter_internetexchange_pdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDefaultExchange',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='default_ix', serialize=False, to='django_fullctl.organization')),
                ('ix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_for_org', to='django_ixctl.internetexchange')),
            ],
            options={
                'verbose_name': 'Organization Default Exchange',
                'verbose_name_plural': 'Organization Default Exchanges',
                'db_table': 'ixctl_default_ix',
            },
        ),
    ]
