# Generated by Django 3.2.18 on 2023-04-25 09:41

from django.db import migrations
import fullctl.django.fields.service_bridge
import fullctl.service_bridge.devicectl


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0016_organizationdefaultexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchangemember',
            name='port',
            field=fullctl.django.fields.service_bridge.ReferencedObjectField(blank=True, bridge=fullctl.service_bridge.devicectl.Port, help_text='deviceCtl port reference', null=True),
        ),
    ]
