# Generated by Django 4.2.9 on 2024-03-14 11:17

import django.db.models.deletion
import django.db.models.manager
import django_handleref.models
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ixctl", "0017_internetexchangemember_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetexchange",
            name="mtu",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="MTU for the exchange", null=True
            ),
        ),
        migrations.AddField(
            model_name="internetexchange",
            name="vlan_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="VLAN ID for the exchange", null=True
            ),
        ),
        migrations.CreateModel(
            name="InternetExchangePrefix",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("prefix", netfields.fields.CidrAddressField(max_length=43)),
                (
                    "ix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefixes",
                        to="django_ixctl.internetexchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internet Exchange Prefix",
                "verbose_name_plural": "Internet Exchange Prefixes",
                "db_table": "ixctl_prefix",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
