# Generated by Django 2.2.16 on 2020-10-19 14:03

from django.db import migrations, models
import django_ixctl.inet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_ixctl', '0017_perm_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetexchangemember',
            name='as_macro',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django_ixctl.inet.validators.validate_as_set]),
        ),
    ]
