# Generated by Django 4.2.9 on 2024-03-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_ixctl", "0018_internetexchange_mtu_internetexchange_vlan_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="internetexchangeprefix",
            unique_together={("prefix", "ix")},
        ),
    ]
